package:
  name: "vtk"
  version: "8.1.0"

build:
  number: 0

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  requires:
    - python
  imports:
    - vtk

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.
